node('aws-codebuild'){

    def CLUSTER = "nasajon-ztapilot"
    def BRANCH = 'development'

    stage('Clean') {
        deleteDir()
    }

    stage('Fetch') {
        timeout(time: 60, unit: 'SECONDS') {
            checkout scm
        }
    }

    def APP_NAME = "angularjs-skeleton"
    def ARGO_NAME = "angularjs-skeleton"

    if (env.BRANCH_NAME == 'development') {
        CLUSTER = "nasajon-ztapilot"
        BRANCH = 'development'
    }
    else if (env.BRANCH_NAME == 'master') {
        CLUSTER = "eks-qa"
        BRANCH = 'master'
        ARGO_NAME = "angularjs-skeleton-qa"
    }
    else if (env.BRANCH_NAME == 'production') {
        CLUSTER = "eks-prod"
        BRANCH = 'production'
    }

    def SPRINT_VERSION = "/opt/devops/Ansible/roles/sprint_up/files/ssm_manager.py"

    stage('Environment Config') {
      sh "auto_config"
    }

    stage('Config') {
        sh "cp src/config/config.json.dist src/config/config.json"
        if (env.BRANCH_NAME == 'production') {
            sh "sed -i 's?api.dev.meutrabalho.app?api.meutrabalho.app?g' src/config/config.json"
            sh "sed -i 's?auth.dev.nasajonsistemas.com.br?auth.nasajon.com.br?g' src/config/config.json"
            sh "sed -i 's?DEV?master?g' src/config/config.json"
            sh "sed -i 's?YW5hZHBjaGF0Ym90ZGV2OmEyZWNlYTQyLTFiMmMtNGNlNS04ZWUxLTNiNzNhNmUxOWY4Ng==?dGVzdGVodHRwMjE6MGMyZjdlYWYtZjAwZC00ZDBkLTliMDgtN2UyNDhlNjFkYWJl?g' src/config/config.json"
        }
        else if (env.BRANCH_NAME == 'master') {
            sh "sed -i 's?api.dev.meutrabalho.app?api.qa.meutrabalho.app?g' src/config/config.json"
            sh "sed -i 's?auth.dev.nasajonsistemas.com.br?auth.nasajonsistemas.com.br?g' src/config/config.json"
            sh "sed -i 's?DEV?QA?g' src/config/config.json"
            sh "sed -i 's?YW5hZHBjaGF0Ym90ZGV2OmEyZWNlYTQyLTFiMmMtNGNlNS04ZWUxLTNiNzNhNmUxOWY4Ng==?YW5hZHBjaGF0Ym90cWE6MTQ4YmFjZGMtMzVlZS00ZWFmLWIzOWItY2VlMzViMzg0MDQ2?g' src/config/config.json"
        }
    }

    stage('Build'){
        docker.image("nasajon/yarn:1.9.4").inside("-v /root/.ssh:/root/.ssh") {
            sh "yarn install"
        }
    }

    stage('Webpack'){
        docker.image("nasajon/yarn:1.9.4").inside("-v /root/.ssh:/root/.ssh -e NODE_ENV=production") {
            sh "node node_modules/.bin/webpack"
        }
    }

    SPRINT = sh (
        script: "python3 $SPRINT_VERSION -p $APP_NAME -m get -b $BRANCH -v sprint",
        returnStdout: true
    ).trim()

    BUILD = sh (
        script: "python3 $SPRINT_VERSION -p $APP_NAME -m get -b $BRANCH -v build",
        returnStdout: true
    ).trim()

    def VERSION = "v2.$SPRINT.$BUILD"

    stage('Docker ship'){
        sh "docker build --no-cache --rm -t hub.nasajon.com.br/$APP_NAME:$VERSION ."
        sh "docker push hub.nasajon.com.br/$APP_NAME:$VERSION"
	    sh "docker rmi -f hub.nasajon.com.br/$APP_NAME:$VERSION"
        sh "python3 $SPRINT_VERSION -p $APP_NAME -m update -b $BRANCH -v build"
    }

    stage('git clone'){
        sh "git clone git@github.com:NasajonSRE/helm.git"
        if (env.BRANCH_NAME == 'production') {
            sh "cp ci/values.yaml helm/charts/projeto-ana/$APP_NAME/values.yaml"
            sh "sed -i \"s/{{ TAG }}/$VERSION/g\" helm/charts/projeto-ana/$APP_NAME/values.yaml"
        }
        else {
            sh "cp ci/values.yaml helm/charts/projeto-ana/$APP_NAME/${ARGO_NAME}-values.yaml"
            sh "sed -i \"s/{{ TAG }}/$VERSION/g\" helm/charts/projeto-ana/$APP_NAME/${ARGO_NAME}-values.yaml"
        }

    	dir("helm/charts/projeto-ana/$APP_NAME"){
        	sh "git add ."
        	sh "git commit -m \"Rendered Helm chart values for $ARGO_NAME - Version $VERSION\""
        	sh "git push -u origin main || true"
	    }
    }

    stage('Deploy'){
        docker.image("hub.nasajon.com.br/sre-utils:0.4").inside() {
            sh "cp /workspace/argo-prod.yaml.j2 /workspace/${ARGO_NAME}-argo.yaml"
            if (env.BRANCH_NAME != 'production') {
                sh "sed -i \"s#- values.yaml#- ${ARGO_NAME}-values.yaml#g\" /workspace/${ARGO_NAME}-argo.yaml"
            }
            sh "sed -i \"s#./charts/{{ APP }}#./charts/projeto-ana/${APP_NAME}#g\" /workspace/${ARGO_NAME}-argo.yaml"
            sh "sed -i \"s/default/ana-common/g\" /workspace/${ARGO_NAME}-argo.yaml"
            sh "sed -i \"s/{{ APP }}/$ARGO_NAME/g\" /workspace/${ARGO_NAME}-argo.yaml"
            sh "sed -i \"s/{{ CLUSTER }}/$CLUSTER/g\" /workspace/${ARGO_NAME}-argo.yaml"
            sh "sed -i \"s/{{ NAMESPACE }}/ana-common/g\" /workspace/${ARGO_NAME}-argo.yaml"
            sh "kubectl --kubeconfig=/workspace/kubeconfig-sre apply -f /workspace/${ARGO_NAME}-argo.yaml"
	    }
    }
}
